# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20170110_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sheet', models.CharField(max_length=48)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
